function out1 = elastic_term(k)
%ELASTIC_TERM
%    OUT1 = ELASTIC_TERM(K)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Feb-2024 12:30:25

out1 = k.*1.035640387666683e-7;
end
