function out1 = input_force(p)
%INPUT_FORCE
%    OUT1 = INPUT_FORCE(P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Feb-2024 12:30:25

out1 = p.*1.256637061435915e-7;
end
