function out1 = input_torque(p)
%INPUT_TORQUE
%    OUT1 = INPUT_TORQUE(P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    22-Apr-2025 11:21:38

out1 = p.*6.09212450043307e-11;
end
