/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generic_system_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {6, 6, 1};
static const casadi_int casadi_s2[3] = {6, 3, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[3] = {60, 1, 1};

/* generic_system_model_expl_vde_forw:(i0[6],i1[6x6],i2[6x3],i3[3],i4[60])->(o0[6],o1[6x6],o2[6x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61;
  a00=arg[4]? arg[4][0] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a02=(a00*a01);
  a03=arg[4]? arg[4][6] : 0;
  a04=arg[0]? arg[0][1] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=arg[4]? arg[4][12] : 0;
  a06=arg[0]? arg[0][2] : 0;
  a07=(a05*a06);
  a02=(a02+a07);
  a07=arg[4]? arg[4][18] : 0;
  a08=arg[0]? arg[0][3] : 0;
  a09=(a07*a08);
  a02=(a02+a09);
  a09=arg[4]? arg[4][24] : 0;
  a10=arg[0]? arg[0][4] : 0;
  a11=(a09*a10);
  a02=(a02+a11);
  a11=arg[4]? arg[4][30] : 0;
  a12=arg[0]? arg[0][5] : 0;
  a13=(a11*a12);
  a02=(a02+a13);
  a13=arg[4]? arg[4][36] : 0;
  a14=arg[3]? arg[3][0] : 0;
  a15=(a13*a14);
  a16=arg[4]? arg[4][42] : 0;
  a17=arg[3]? arg[3][1] : 0;
  a18=(a16*a17);
  a15=(a15+a18);
  a18=arg[4]? arg[4][48] : 0;
  a19=arg[3]? arg[3][2] : 0;
  a20=(a18*a19);
  a15=(a15+a20);
  a02=(a02+a15);
  a15=arg[4]? arg[4][54] : 0;
  a02=(a02+a15);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[4]? arg[4][1] : 0;
  a15=(a02*a01);
  a20=arg[4]? arg[4][7] : 0;
  a21=(a20*a04);
  a15=(a15+a21);
  a21=arg[4]? arg[4][13] : 0;
  a22=(a21*a06);
  a15=(a15+a22);
  a22=arg[4]? arg[4][19] : 0;
  a23=(a22*a08);
  a15=(a15+a23);
  a23=arg[4]? arg[4][25] : 0;
  a24=(a23*a10);
  a15=(a15+a24);
  a24=arg[4]? arg[4][31] : 0;
  a25=(a24*a12);
  a15=(a15+a25);
  a25=arg[4]? arg[4][37] : 0;
  a26=(a25*a14);
  a27=arg[4]? arg[4][43] : 0;
  a28=(a27*a17);
  a26=(a26+a28);
  a28=arg[4]? arg[4][49] : 0;
  a29=(a28*a19);
  a26=(a26+a29);
  a15=(a15+a26);
  a26=arg[4]? arg[4][55] : 0;
  a15=(a15+a26);
  if (res[0]!=0) res[0][1]=a15;
  a15=arg[4]? arg[4][2] : 0;
  a26=(a15*a01);
  a29=arg[4]? arg[4][8] : 0;
  a30=(a29*a04);
  a26=(a26+a30);
  a30=arg[4]? arg[4][14] : 0;
  a31=(a30*a06);
  a26=(a26+a31);
  a31=arg[4]? arg[4][20] : 0;
  a32=(a31*a08);
  a26=(a26+a32);
  a32=arg[4]? arg[4][26] : 0;
  a33=(a32*a10);
  a26=(a26+a33);
  a33=arg[4]? arg[4][32] : 0;
  a34=(a33*a12);
  a26=(a26+a34);
  a34=arg[4]? arg[4][38] : 0;
  a35=(a34*a14);
  a36=arg[4]? arg[4][44] : 0;
  a37=(a36*a17);
  a35=(a35+a37);
  a37=arg[4]? arg[4][50] : 0;
  a38=(a37*a19);
  a35=(a35+a38);
  a26=(a26+a35);
  a35=arg[4]? arg[4][56] : 0;
  a26=(a26+a35);
  if (res[0]!=0) res[0][2]=a26;
  a26=arg[4]? arg[4][3] : 0;
  a35=(a26*a01);
  a38=arg[4]? arg[4][9] : 0;
  a39=(a38*a04);
  a35=(a35+a39);
  a39=arg[4]? arg[4][15] : 0;
  a40=(a39*a06);
  a35=(a35+a40);
  a40=arg[4]? arg[4][21] : 0;
  a41=(a40*a08);
  a35=(a35+a41);
  a41=arg[4]? arg[4][27] : 0;
  a42=(a41*a10);
  a35=(a35+a42);
  a42=arg[4]? arg[4][33] : 0;
  a43=(a42*a12);
  a35=(a35+a43);
  a43=arg[4]? arg[4][39] : 0;
  a44=(a43*a14);
  a45=arg[4]? arg[4][45] : 0;
  a46=(a45*a17);
  a44=(a44+a46);
  a46=arg[4]? arg[4][51] : 0;
  a47=(a46*a19);
  a44=(a44+a47);
  a35=(a35+a44);
  a44=arg[4]? arg[4][57] : 0;
  a35=(a35+a44);
  if (res[0]!=0) res[0][3]=a35;
  a35=arg[4]? arg[4][4] : 0;
  a44=(a35*a01);
  a47=arg[4]? arg[4][10] : 0;
  a48=(a47*a04);
  a44=(a44+a48);
  a48=arg[4]? arg[4][16] : 0;
  a49=(a48*a06);
  a44=(a44+a49);
  a49=arg[4]? arg[4][22] : 0;
  a50=(a49*a08);
  a44=(a44+a50);
  a50=arg[4]? arg[4][28] : 0;
  a51=(a50*a10);
  a44=(a44+a51);
  a51=arg[4]? arg[4][34] : 0;
  a52=(a51*a12);
  a44=(a44+a52);
  a52=arg[4]? arg[4][40] : 0;
  a53=(a52*a14);
  a54=arg[4]? arg[4][46] : 0;
  a55=(a54*a17);
  a53=(a53+a55);
  a55=arg[4]? arg[4][52] : 0;
  a56=(a55*a19);
  a53=(a53+a56);
  a44=(a44+a53);
  a53=arg[4]? arg[4][58] : 0;
  a44=(a44+a53);
  if (res[0]!=0) res[0][4]=a44;
  a44=arg[4]? arg[4][5] : 0;
  a01=(a44*a01);
  a53=arg[4]? arg[4][11] : 0;
  a04=(a53*a04);
  a01=(a01+a04);
  a04=arg[4]? arg[4][17] : 0;
  a06=(a04*a06);
  a01=(a01+a06);
  a06=arg[4]? arg[4][23] : 0;
  a08=(a06*a08);
  a01=(a01+a08);
  a08=arg[4]? arg[4][29] : 0;
  a10=(a08*a10);
  a01=(a01+a10);
  a10=arg[4]? arg[4][35] : 0;
  a12=(a10*a12);
  a01=(a01+a12);
  a12=arg[4]? arg[4][41] : 0;
  a14=(a12*a14);
  a56=arg[4]? arg[4][47] : 0;
  a17=(a56*a17);
  a14=(a14+a17);
  a17=arg[4]? arg[4][53] : 0;
  a19=(a17*a19);
  a14=(a14+a19);
  a01=(a01+a14);
  a14=arg[4]? arg[4][59] : 0;
  a01=(a01+a14);
  if (res[0]!=0) res[0][5]=a01;
  a01=arg[1]? arg[1][0] : 0;
  a14=(a00*a01);
  a19=arg[1]? arg[1][1] : 0;
  a57=(a03*a19);
  a14=(a14+a57);
  a57=arg[1]? arg[1][2] : 0;
  a58=(a05*a57);
  a14=(a14+a58);
  a58=arg[1]? arg[1][3] : 0;
  a59=(a07*a58);
  a14=(a14+a59);
  a59=arg[1]? arg[1][4] : 0;
  a60=(a09*a59);
  a14=(a14+a60);
  a60=arg[1]? arg[1][5] : 0;
  a61=(a11*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][0]=a14;
  a14=(a02*a01);
  a61=(a20*a19);
  a14=(a14+a61);
  a61=(a21*a57);
  a14=(a14+a61);
  a61=(a22*a58);
  a14=(a14+a61);
  a61=(a23*a59);
  a14=(a14+a61);
  a61=(a24*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][1]=a14;
  a14=(a15*a01);
  a61=(a29*a19);
  a14=(a14+a61);
  a61=(a30*a57);
  a14=(a14+a61);
  a61=(a31*a58);
  a14=(a14+a61);
  a61=(a32*a59);
  a14=(a14+a61);
  a61=(a33*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][2]=a14;
  a14=(a26*a01);
  a61=(a38*a19);
  a14=(a14+a61);
  a61=(a39*a57);
  a14=(a14+a61);
  a61=(a40*a58);
  a14=(a14+a61);
  a61=(a41*a59);
  a14=(a14+a61);
  a61=(a42*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][3]=a14;
  a14=(a35*a01);
  a61=(a47*a19);
  a14=(a14+a61);
  a61=(a48*a57);
  a14=(a14+a61);
  a61=(a49*a58);
  a14=(a14+a61);
  a61=(a50*a59);
  a14=(a14+a61);
  a61=(a51*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][4]=a14;
  a01=(a44*a01);
  a19=(a53*a19);
  a01=(a01+a19);
  a57=(a04*a57);
  a01=(a01+a57);
  a58=(a06*a58);
  a01=(a01+a58);
  a59=(a08*a59);
  a01=(a01+a59);
  a60=(a10*a60);
  a01=(a01+a60);
  if (res[1]!=0) res[1][5]=a01;
  a01=arg[1]? arg[1][6] : 0;
  a60=(a00*a01);
  a59=arg[1]? arg[1][7] : 0;
  a58=(a03*a59);
  a60=(a60+a58);
  a58=arg[1]? arg[1][8] : 0;
  a57=(a05*a58);
  a60=(a60+a57);
  a57=arg[1]? arg[1][9] : 0;
  a19=(a07*a57);
  a60=(a60+a19);
  a19=arg[1]? arg[1][10] : 0;
  a14=(a09*a19);
  a60=(a60+a14);
  a14=arg[1]? arg[1][11] : 0;
  a61=(a11*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][6]=a60;
  a60=(a02*a01);
  a61=(a20*a59);
  a60=(a60+a61);
  a61=(a21*a58);
  a60=(a60+a61);
  a61=(a22*a57);
  a60=(a60+a61);
  a61=(a23*a19);
  a60=(a60+a61);
  a61=(a24*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][7]=a60;
  a60=(a15*a01);
  a61=(a29*a59);
  a60=(a60+a61);
  a61=(a30*a58);
  a60=(a60+a61);
  a61=(a31*a57);
  a60=(a60+a61);
  a61=(a32*a19);
  a60=(a60+a61);
  a61=(a33*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][8]=a60;
  a60=(a26*a01);
  a61=(a38*a59);
  a60=(a60+a61);
  a61=(a39*a58);
  a60=(a60+a61);
  a61=(a40*a57);
  a60=(a60+a61);
  a61=(a41*a19);
  a60=(a60+a61);
  a61=(a42*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][9]=a60;
  a60=(a35*a01);
  a61=(a47*a59);
  a60=(a60+a61);
  a61=(a48*a58);
  a60=(a60+a61);
  a61=(a49*a57);
  a60=(a60+a61);
  a61=(a50*a19);
  a60=(a60+a61);
  a61=(a51*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][10]=a60;
  a01=(a44*a01);
  a59=(a53*a59);
  a01=(a01+a59);
  a58=(a04*a58);
  a01=(a01+a58);
  a57=(a06*a57);
  a01=(a01+a57);
  a19=(a08*a19);
  a01=(a01+a19);
  a14=(a10*a14);
  a01=(a01+a14);
  if (res[1]!=0) res[1][11]=a01;
  a01=arg[1]? arg[1][12] : 0;
  a14=(a00*a01);
  a19=arg[1]? arg[1][13] : 0;
  a57=(a03*a19);
  a14=(a14+a57);
  a57=arg[1]? arg[1][14] : 0;
  a58=(a05*a57);
  a14=(a14+a58);
  a58=arg[1]? arg[1][15] : 0;
  a59=(a07*a58);
  a14=(a14+a59);
  a59=arg[1]? arg[1][16] : 0;
  a60=(a09*a59);
  a14=(a14+a60);
  a60=arg[1]? arg[1][17] : 0;
  a61=(a11*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][12]=a14;
  a14=(a02*a01);
  a61=(a20*a19);
  a14=(a14+a61);
  a61=(a21*a57);
  a14=(a14+a61);
  a61=(a22*a58);
  a14=(a14+a61);
  a61=(a23*a59);
  a14=(a14+a61);
  a61=(a24*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][13]=a14;
  a14=(a15*a01);
  a61=(a29*a19);
  a14=(a14+a61);
  a61=(a30*a57);
  a14=(a14+a61);
  a61=(a31*a58);
  a14=(a14+a61);
  a61=(a32*a59);
  a14=(a14+a61);
  a61=(a33*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][14]=a14;
  a14=(a26*a01);
  a61=(a38*a19);
  a14=(a14+a61);
  a61=(a39*a57);
  a14=(a14+a61);
  a61=(a40*a58);
  a14=(a14+a61);
  a61=(a41*a59);
  a14=(a14+a61);
  a61=(a42*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][15]=a14;
  a14=(a35*a01);
  a61=(a47*a19);
  a14=(a14+a61);
  a61=(a48*a57);
  a14=(a14+a61);
  a61=(a49*a58);
  a14=(a14+a61);
  a61=(a50*a59);
  a14=(a14+a61);
  a61=(a51*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][16]=a14;
  a01=(a44*a01);
  a19=(a53*a19);
  a01=(a01+a19);
  a57=(a04*a57);
  a01=(a01+a57);
  a58=(a06*a58);
  a01=(a01+a58);
  a59=(a08*a59);
  a01=(a01+a59);
  a60=(a10*a60);
  a01=(a01+a60);
  if (res[1]!=0) res[1][17]=a01;
  a01=arg[1]? arg[1][18] : 0;
  a60=(a00*a01);
  a59=arg[1]? arg[1][19] : 0;
  a58=(a03*a59);
  a60=(a60+a58);
  a58=arg[1]? arg[1][20] : 0;
  a57=(a05*a58);
  a60=(a60+a57);
  a57=arg[1]? arg[1][21] : 0;
  a19=(a07*a57);
  a60=(a60+a19);
  a19=arg[1]? arg[1][22] : 0;
  a14=(a09*a19);
  a60=(a60+a14);
  a14=arg[1]? arg[1][23] : 0;
  a61=(a11*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][18]=a60;
  a60=(a02*a01);
  a61=(a20*a59);
  a60=(a60+a61);
  a61=(a21*a58);
  a60=(a60+a61);
  a61=(a22*a57);
  a60=(a60+a61);
  a61=(a23*a19);
  a60=(a60+a61);
  a61=(a24*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][19]=a60;
  a60=(a15*a01);
  a61=(a29*a59);
  a60=(a60+a61);
  a61=(a30*a58);
  a60=(a60+a61);
  a61=(a31*a57);
  a60=(a60+a61);
  a61=(a32*a19);
  a60=(a60+a61);
  a61=(a33*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][20]=a60;
  a60=(a26*a01);
  a61=(a38*a59);
  a60=(a60+a61);
  a61=(a39*a58);
  a60=(a60+a61);
  a61=(a40*a57);
  a60=(a60+a61);
  a61=(a41*a19);
  a60=(a60+a61);
  a61=(a42*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][21]=a60;
  a60=(a35*a01);
  a61=(a47*a59);
  a60=(a60+a61);
  a61=(a48*a58);
  a60=(a60+a61);
  a61=(a49*a57);
  a60=(a60+a61);
  a61=(a50*a19);
  a60=(a60+a61);
  a61=(a51*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][22]=a60;
  a01=(a44*a01);
  a59=(a53*a59);
  a01=(a01+a59);
  a58=(a04*a58);
  a01=(a01+a58);
  a57=(a06*a57);
  a01=(a01+a57);
  a19=(a08*a19);
  a01=(a01+a19);
  a14=(a10*a14);
  a01=(a01+a14);
  if (res[1]!=0) res[1][23]=a01;
  a01=arg[1]? arg[1][24] : 0;
  a14=(a00*a01);
  a19=arg[1]? arg[1][25] : 0;
  a57=(a03*a19);
  a14=(a14+a57);
  a57=arg[1]? arg[1][26] : 0;
  a58=(a05*a57);
  a14=(a14+a58);
  a58=arg[1]? arg[1][27] : 0;
  a59=(a07*a58);
  a14=(a14+a59);
  a59=arg[1]? arg[1][28] : 0;
  a60=(a09*a59);
  a14=(a14+a60);
  a60=arg[1]? arg[1][29] : 0;
  a61=(a11*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][24]=a14;
  a14=(a02*a01);
  a61=(a20*a19);
  a14=(a14+a61);
  a61=(a21*a57);
  a14=(a14+a61);
  a61=(a22*a58);
  a14=(a14+a61);
  a61=(a23*a59);
  a14=(a14+a61);
  a61=(a24*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][25]=a14;
  a14=(a15*a01);
  a61=(a29*a19);
  a14=(a14+a61);
  a61=(a30*a57);
  a14=(a14+a61);
  a61=(a31*a58);
  a14=(a14+a61);
  a61=(a32*a59);
  a14=(a14+a61);
  a61=(a33*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][26]=a14;
  a14=(a26*a01);
  a61=(a38*a19);
  a14=(a14+a61);
  a61=(a39*a57);
  a14=(a14+a61);
  a61=(a40*a58);
  a14=(a14+a61);
  a61=(a41*a59);
  a14=(a14+a61);
  a61=(a42*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][27]=a14;
  a14=(a35*a01);
  a61=(a47*a19);
  a14=(a14+a61);
  a61=(a48*a57);
  a14=(a14+a61);
  a61=(a49*a58);
  a14=(a14+a61);
  a61=(a50*a59);
  a14=(a14+a61);
  a61=(a51*a60);
  a14=(a14+a61);
  if (res[1]!=0) res[1][28]=a14;
  a01=(a44*a01);
  a19=(a53*a19);
  a01=(a01+a19);
  a57=(a04*a57);
  a01=(a01+a57);
  a58=(a06*a58);
  a01=(a01+a58);
  a59=(a08*a59);
  a01=(a01+a59);
  a60=(a10*a60);
  a01=(a01+a60);
  if (res[1]!=0) res[1][29]=a01;
  a01=arg[1]? arg[1][30] : 0;
  a60=(a00*a01);
  a59=arg[1]? arg[1][31] : 0;
  a58=(a03*a59);
  a60=(a60+a58);
  a58=arg[1]? arg[1][32] : 0;
  a57=(a05*a58);
  a60=(a60+a57);
  a57=arg[1]? arg[1][33] : 0;
  a19=(a07*a57);
  a60=(a60+a19);
  a19=arg[1]? arg[1][34] : 0;
  a14=(a09*a19);
  a60=(a60+a14);
  a14=arg[1]? arg[1][35] : 0;
  a61=(a11*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][30]=a60;
  a60=(a02*a01);
  a61=(a20*a59);
  a60=(a60+a61);
  a61=(a21*a58);
  a60=(a60+a61);
  a61=(a22*a57);
  a60=(a60+a61);
  a61=(a23*a19);
  a60=(a60+a61);
  a61=(a24*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][31]=a60;
  a60=(a15*a01);
  a61=(a29*a59);
  a60=(a60+a61);
  a61=(a30*a58);
  a60=(a60+a61);
  a61=(a31*a57);
  a60=(a60+a61);
  a61=(a32*a19);
  a60=(a60+a61);
  a61=(a33*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][32]=a60;
  a60=(a26*a01);
  a61=(a38*a59);
  a60=(a60+a61);
  a61=(a39*a58);
  a60=(a60+a61);
  a61=(a40*a57);
  a60=(a60+a61);
  a61=(a41*a19);
  a60=(a60+a61);
  a61=(a42*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][33]=a60;
  a60=(a35*a01);
  a61=(a47*a59);
  a60=(a60+a61);
  a61=(a48*a58);
  a60=(a60+a61);
  a61=(a49*a57);
  a60=(a60+a61);
  a61=(a50*a19);
  a60=(a60+a61);
  a61=(a51*a14);
  a60=(a60+a61);
  if (res[1]!=0) res[1][34]=a60;
  a01=(a44*a01);
  a59=(a53*a59);
  a01=(a01+a59);
  a58=(a04*a58);
  a01=(a01+a58);
  a57=(a06*a57);
  a01=(a01+a57);
  a19=(a08*a19);
  a01=(a01+a19);
  a14=(a10*a14);
  a01=(a01+a14);
  if (res[1]!=0) res[1][35]=a01;
  a01=arg[2]? arg[2][0] : 0;
  a14=(a00*a01);
  a19=arg[2]? arg[2][1] : 0;
  a57=(a03*a19);
  a14=(a14+a57);
  a57=arg[2]? arg[2][2] : 0;
  a58=(a05*a57);
  a14=(a14+a58);
  a58=arg[2]? arg[2][3] : 0;
  a59=(a07*a58);
  a14=(a14+a59);
  a59=arg[2]? arg[2][4] : 0;
  a60=(a09*a59);
  a14=(a14+a60);
  a60=arg[2]? arg[2][5] : 0;
  a61=(a11*a60);
  a14=(a14+a61);
  a13=(a13+a14);
  if (res[2]!=0) res[2][0]=a13;
  a13=(a02*a01);
  a14=(a20*a19);
  a13=(a13+a14);
  a14=(a21*a57);
  a13=(a13+a14);
  a14=(a22*a58);
  a13=(a13+a14);
  a14=(a23*a59);
  a13=(a13+a14);
  a14=(a24*a60);
  a13=(a13+a14);
  a25=(a25+a13);
  if (res[2]!=0) res[2][1]=a25;
  a25=(a15*a01);
  a13=(a29*a19);
  a25=(a25+a13);
  a13=(a30*a57);
  a25=(a25+a13);
  a13=(a31*a58);
  a25=(a25+a13);
  a13=(a32*a59);
  a25=(a25+a13);
  a13=(a33*a60);
  a25=(a25+a13);
  a34=(a34+a25);
  if (res[2]!=0) res[2][2]=a34;
  a34=(a26*a01);
  a25=(a38*a19);
  a34=(a34+a25);
  a25=(a39*a57);
  a34=(a34+a25);
  a25=(a40*a58);
  a34=(a34+a25);
  a25=(a41*a59);
  a34=(a34+a25);
  a25=(a42*a60);
  a34=(a34+a25);
  a43=(a43+a34);
  if (res[2]!=0) res[2][3]=a43;
  a43=(a35*a01);
  a34=(a47*a19);
  a43=(a43+a34);
  a34=(a48*a57);
  a43=(a43+a34);
  a34=(a49*a58);
  a43=(a43+a34);
  a34=(a50*a59);
  a43=(a43+a34);
  a34=(a51*a60);
  a43=(a43+a34);
  a52=(a52+a43);
  if (res[2]!=0) res[2][4]=a52;
  a01=(a44*a01);
  a19=(a53*a19);
  a01=(a01+a19);
  a57=(a04*a57);
  a01=(a01+a57);
  a58=(a06*a58);
  a01=(a01+a58);
  a59=(a08*a59);
  a01=(a01+a59);
  a60=(a10*a60);
  a01=(a01+a60);
  a12=(a12+a01);
  if (res[2]!=0) res[2][5]=a12;
  a12=arg[2]? arg[2][6] : 0;
  a01=(a00*a12);
  a60=arg[2]? arg[2][7] : 0;
  a59=(a03*a60);
  a01=(a01+a59);
  a59=arg[2]? arg[2][8] : 0;
  a58=(a05*a59);
  a01=(a01+a58);
  a58=arg[2]? arg[2][9] : 0;
  a57=(a07*a58);
  a01=(a01+a57);
  a57=arg[2]? arg[2][10] : 0;
  a19=(a09*a57);
  a01=(a01+a19);
  a19=arg[2]? arg[2][11] : 0;
  a52=(a11*a19);
  a01=(a01+a52);
  a16=(a16+a01);
  if (res[2]!=0) res[2][6]=a16;
  a16=(a02*a12);
  a01=(a20*a60);
  a16=(a16+a01);
  a01=(a21*a59);
  a16=(a16+a01);
  a01=(a22*a58);
  a16=(a16+a01);
  a01=(a23*a57);
  a16=(a16+a01);
  a01=(a24*a19);
  a16=(a16+a01);
  a27=(a27+a16);
  if (res[2]!=0) res[2][7]=a27;
  a27=(a15*a12);
  a16=(a29*a60);
  a27=(a27+a16);
  a16=(a30*a59);
  a27=(a27+a16);
  a16=(a31*a58);
  a27=(a27+a16);
  a16=(a32*a57);
  a27=(a27+a16);
  a16=(a33*a19);
  a27=(a27+a16);
  a36=(a36+a27);
  if (res[2]!=0) res[2][8]=a36;
  a36=(a26*a12);
  a27=(a38*a60);
  a36=(a36+a27);
  a27=(a39*a59);
  a36=(a36+a27);
  a27=(a40*a58);
  a36=(a36+a27);
  a27=(a41*a57);
  a36=(a36+a27);
  a27=(a42*a19);
  a36=(a36+a27);
  a45=(a45+a36);
  if (res[2]!=0) res[2][9]=a45;
  a45=(a35*a12);
  a36=(a47*a60);
  a45=(a45+a36);
  a36=(a48*a59);
  a45=(a45+a36);
  a36=(a49*a58);
  a45=(a45+a36);
  a36=(a50*a57);
  a45=(a45+a36);
  a36=(a51*a19);
  a45=(a45+a36);
  a54=(a54+a45);
  if (res[2]!=0) res[2][10]=a54;
  a12=(a44*a12);
  a60=(a53*a60);
  a12=(a12+a60);
  a59=(a04*a59);
  a12=(a12+a59);
  a58=(a06*a58);
  a12=(a12+a58);
  a57=(a08*a57);
  a12=(a12+a57);
  a19=(a10*a19);
  a12=(a12+a19);
  a56=(a56+a12);
  if (res[2]!=0) res[2][11]=a56;
  a56=arg[2]? arg[2][12] : 0;
  a00=(a00*a56);
  a12=arg[2]? arg[2][13] : 0;
  a03=(a03*a12);
  a00=(a00+a03);
  a03=arg[2]? arg[2][14] : 0;
  a05=(a05*a03);
  a00=(a00+a05);
  a05=arg[2]? arg[2][15] : 0;
  a07=(a07*a05);
  a00=(a00+a07);
  a07=arg[2]? arg[2][16] : 0;
  a09=(a09*a07);
  a00=(a00+a09);
  a09=arg[2]? arg[2][17] : 0;
  a11=(a11*a09);
  a00=(a00+a11);
  a18=(a18+a00);
  if (res[2]!=0) res[2][12]=a18;
  a02=(a02*a56);
  a20=(a20*a12);
  a02=(a02+a20);
  a21=(a21*a03);
  a02=(a02+a21);
  a22=(a22*a05);
  a02=(a02+a22);
  a23=(a23*a07);
  a02=(a02+a23);
  a24=(a24*a09);
  a02=(a02+a24);
  a28=(a28+a02);
  if (res[2]!=0) res[2][13]=a28;
  a15=(a15*a56);
  a29=(a29*a12);
  a15=(a15+a29);
  a30=(a30*a03);
  a15=(a15+a30);
  a31=(a31*a05);
  a15=(a15+a31);
  a32=(a32*a07);
  a15=(a15+a32);
  a33=(a33*a09);
  a15=(a15+a33);
  a37=(a37+a15);
  if (res[2]!=0) res[2][14]=a37;
  a26=(a26*a56);
  a38=(a38*a12);
  a26=(a26+a38);
  a39=(a39*a03);
  a26=(a26+a39);
  a40=(a40*a05);
  a26=(a26+a40);
  a41=(a41*a07);
  a26=(a26+a41);
  a42=(a42*a09);
  a26=(a26+a42);
  a46=(a46+a26);
  if (res[2]!=0) res[2][15]=a46;
  a35=(a35*a56);
  a47=(a47*a12);
  a35=(a35+a47);
  a48=(a48*a03);
  a35=(a35+a48);
  a49=(a49*a05);
  a35=(a35+a49);
  a50=(a50*a07);
  a35=(a35+a50);
  a51=(a51*a09);
  a35=(a35+a51);
  a55=(a55+a35);
  if (res[2]!=0) res[2][16]=a55;
  a44=(a44*a56);
  a53=(a53*a12);
  a44=(a44+a53);
  a04=(a04*a03);
  a44=(a44+a04);
  a06=(a06*a05);
  a44=(a44+a06);
  a08=(a08*a07);
  a44=(a44+a08);
  a10=(a10*a09);
  a44=(a44+a10);
  a17=(a17+a44);
  if (res[2]!=0) res[2][17]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int generic_system_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int generic_system_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real generic_system_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* generic_system_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* generic_system_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* generic_system_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* generic_system_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
