/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generic_system_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {60, 1, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};

/* generic_system_model_expl_vde_adj:(i0[6],i1[6],i2[3],i3[60])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=arg[3]? arg[3][5] : 0;
  a1=arg[1]? arg[1][5] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][4] : 0;
  a3=arg[1]? arg[1][4] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][3] : 0;
  a4=arg[1]? arg[1][3] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][2] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][1] : 0;
  a6=arg[1]? arg[1][1] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][0] : 0;
  a7=arg[1]? arg[1][0] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3]? arg[3][11] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][10] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][9] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][8] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][7] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][6] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3]? arg[3][17] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][16] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][15] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][14] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][13] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][12] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3]? arg[3][23] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][22] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][21] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][20] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][19] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][18] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[3]? arg[3][29] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][28] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][27] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][26] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][25] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][24] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[3]? arg[3][35] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][34] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][33] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][32] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][31] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][30] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[3]? arg[3][41] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][40] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][39] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][38] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][37] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][36] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[3]? arg[3][47] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][46] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][45] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][44] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][43] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][42] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[3]? arg[3][53] : 0;
  a0=(a0*a1);
  a1=arg[3]? arg[3][52] : 0;
  a1=(a1*a3);
  a0=(a0+a1);
  a1=arg[3]? arg[3][51] : 0;
  a1=(a1*a4);
  a0=(a0+a1);
  a1=arg[3]? arg[3][50] : 0;
  a1=(a1*a5);
  a0=(a0+a1);
  a1=arg[3]? arg[3][49] : 0;
  a1=(a1*a6);
  a0=(a0+a1);
  a1=arg[3]? arg[3][48] : 0;
  a1=(a1*a7);
  a0=(a0+a1);
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int generic_system_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int generic_system_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real generic_system_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* generic_system_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* generic_system_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* generic_system_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* generic_system_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
