function out1 = elastic_term(k)
%ELASTIC_TERM
%    OUT1 = ELASTIC_TERM(K)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    22-Apr-2025 11:21:39

out1 = k.*1.035336189520879e-7;
end
