function out1 = input_torque(p)
%INPUT_TORQUE
%    OUT1 = INPUT_TORQUE(P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Feb-2024 12:30:25

out1 = p.*6.084098300096448e-11;
end
