function out1 = elastic_term_epsilon(epsilon)
%ELASTIC_TERM_EPSILON
%    OUT1 = ELASTIC_TERM_EPSILON(EPSILON)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    22-Apr-2025 11:21:39

out1 = epsilon.*9.713023401390447e-1;
end
